# Workflow name
name: First Workflow

# manually trigger
on: workflow_dispatch

jobs:
  first-job:
    # define environment
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"

      - name: Print goodbye
        run: echo "Done - bye!"

      - name: Run Multiple Commands
        run: |
          echo "First output"
          echo "Second output"
