name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output environment information
        run: echo "The job is running on  ${{ toJSON(github) }}"
      - name: Output Github context
        # ${{ }} is an expression
        run: echo "My name is ${{ github.actor }}"